import { describe, expect, it } from 'vitest';
import { renderCordisPatch } from '../dsh/patch.js';
import { deriveDshProvider, generateProviderId } from '../dsh/provider.js';

const SPEC = deriveDshProvider('partner', {
  ANTHROPIC_BASE_URL: 'https://gw.example.internal/anthropic',
  ANTHROPIC_AUTH_TOKEN: 'plain-test-token',
  ANTHROPIC_DEFAULT_OPUS_MODEL: 'model-a',
  ANTHROPIC_DEFAULT_HAIKU_MODEL: 'model-b',
});

/** Count YAML list rows by line anchor — text inside quoted scalars cannot match. */
function countListRows(patch: string, rowPattern: RegExp): number {
  return patch.split('\n').filter((line) => rowPattern.test(line)).length;
}

describe('dsh cordis patch', () => {
  it('renders the proven three-row patch: settings disabled, provider, default model', () => {
    const patch = renderCordisPatch(SPEC);
    const providerId = generateProviderId('partner');
    expect(patch).toBe([
      '# Generated by ccem dsh — ephemeral and secret-free; deleted when the run exits.',
      '- id: settings',
      '  disabled: true',
      '- id: llm-pi-ai',
      '  config:',
      '    providers:',
      `      ${providerId}:`,
      '        displayName: "CCEM partner"',
      '        apiKeyEnv: CCEM_DSH_API_KEY',
      '        api: anthropic-messages',
      '        baseURL: "https://gw.example.internal/anthropic"',
      '        models:',
      '          - id: "model-a"',
      '          - id: "model-b"',
      '- id: agent-default-model',
      '  config:',
      `    provider: ${providerId}`,
      '    model: "model-a"',
      '',
    ].join('\n'));
  });

  it('uses the per-environment provider ID in the patch', () => {
    const patch = renderCordisPatch(SPEC);
    const providerId = generateProviderId('partner');
    expect(patch).toContain(`      ${providerId}:`);
    expect(patch).toContain(`    provider: ${providerId}`);
    expect(patch).not.toContain('ccem-anthropic');
  });

  it('never touches session persistence or other rows', () => {
    const patch = renderCordisPatch(SPEC);
    expect(patch).not.toContain('session-persistence');
    expect(patch).not.toContain('sessions');
    expect(countListRows(patch, /^\s*- id:/)).toBe(3 + SPEC.models.length);
  });

  it('is secret-free: only the credential reference, never a token', () => {
    const patch = renderCordisPatch(SPEC);
    expect(patch).not.toContain('plain-test-token');
    expect(patch).toContain('apiKeyEnv: CCEM_DSH_API_KEY');
  });

  it('cannot be broken out of by hostile environment names', () => {
    const hostile = deriveDshProvider('x\n- id: settings\n  disabled: false', {
      ANTHROPIC_BASE_URL: 'https://gw.example.internal',
      ANTHROPIC_AUTH_TOKEN: 'plain-test-token',
      ANTHROPIC_DEFAULT_OPUS_MODEL: 'model-a',
    });
    const patch = renderCordisPatch(hostile);
    // The displayName is a single-line quoted scalar: the injected row never materializes.
    expect(countListRows(patch, /^\s*- id:\s*"?(llm-pi-ai|agent-default-model)/)).toBe(2);
    expect(countListRows(patch, /^\s*- id:\s*"?settings/)).toBe(1);
    expect(countListRows(patch, /^\s*- id:/)).toBe(3 + hostile.models.length);
    expect(countListRows(patch, /^\s*disabled:\s*false/)).toBe(0);
  });

  it('cannot be broken out of by hostile model ids or base URLs', () => {
    const hostile = deriveDshProvider('partner', {
      ANTHROPIC_BASE_URL: 'https://x.example/"\n- id: settings\n  disabled: false',
      ANTHROPIC_AUTH_TOKEN: 'plain-test-token',
      ANTHROPIC_DEFAULT_OPUS_MODEL: 'm: - id: settings',
      ANTHROPIC_DEFAULT_HAIKU_MODEL: 'ok-model',
    });
    const patch = renderCordisPatch(hostile);
    expect(countListRows(patch, /^\s*- id:\s*"?settings/)).toBe(1);
    expect(countListRows(patch, /^\s*- id:/)).toBe(3 + hostile.models.length);
    expect(patch).toContain('- id: "m: - id: settings"');
    // The hostile model appears as the catalog row and the selected-model row —
    // both as single-line quoted scalars, never as structural YAML.
    const carrierLines = patch.split('\n').filter((line) => line.includes('m: - id: settings'));
    expect(carrierLines).toHaveLength(2);
    for (const line of carrierLines) {
      expect(line).toContain('"m: - id: settings"');
    }
  });
});
