import type { DshProviderSpec } from './provider.js';
import { DSH_API_KEY_ENV, DSH_PROTOCOL } from './provider.js';

/**
 * Renders the ephemeral, secret-free Cordis patch passed to dsh via
 * `--patch`.
 *
 * Layer order (verified against dsh 0.1.1-rc.2 `--dump-config`): bundle
 * layers → the profile's `cordis.patch.yml` user layer → `--patch` overlays.
 *
 * - `settings` is disabled: a live settings document would let the user's
 *   `settings.yaml` in the active dsh root override this run's
 *   provider/model/baseURL, so the composition base plus this patch becomes
 *   the whole configuration surface (deterministic isolation). Session
 *   persistence is untouched and keeps its `dshHomePath('sessions')` root,
 *   so session logs still land in the active dsh root.
 * - `llm-pi-ai.providers[<providerId>]` declares a hand-declared
 *   `anthropic-messages` route; `apiKeyEnv` is a credential reference — the
 *   token itself travels only in the child environment.
 * - `agent-default-model` pins the route and the selected model.
 */

const IDENTIFIER_PATTERN = /^[A-Za-z0-9][\w./-]*$/;

/**
 * Emit a YAML scalar. Trusted ccem-controlled identifiers stay bare;
 * everything user-derived (display names, URLs, model ids) is emitted as a
 * JSON string, which is a single-line YAML double-quoted scalar — a hostile
 * value can never break out into new YAML nodes.
 */
function yamlScalar(value: string, trusted = false): string {
  if (trusted && IDENTIFIER_PATTERN.test(value)) return value;
  return JSON.stringify(value);
}

export function renderCordisPatch(spec: DshProviderSpec): string {
  const lines: string[] = [
    '# Generated by ccem dsh — ephemeral and secret-free; deleted when the run exits.',
    '- id: settings',
    '  disabled: true',
    '- id: llm-pi-ai',
    '  config:',
    '    providers:',
    `      ${yamlScalar(spec.providerId, true)}:`,
    `        displayName: ${yamlScalar(spec.displayName)}`,
    `        apiKeyEnv: ${yamlScalar(DSH_API_KEY_ENV, true)}`,
    `        api: ${DSH_PROTOCOL}`,
    `        baseURL: ${yamlScalar(spec.baseURL)}`,
    '        models:',
  ];

  for (const model of spec.models) {
    lines.push(`          - id: ${yamlScalar(model)}`);
  }

  lines.push(
    '- id: agent-default-model',
    '  config:',
    `    provider: ${yamlScalar(spec.providerId, true)}`,
    `    model: ${yamlScalar(spec.selectedModel)}`,
  );

  return `${lines.join('\n')}\n`;
}
